FROM redhat/ubi9:9.5-1741600006 AS tzdata
RUN dnf install -y tzdata

FROM minio/minio:RELEASE.2025-02-28T09-55-16Z

COPY --from=tzdata /usr/share/zoneinfo /usr/share/zoneinfo
ENV TZ=Europe/Moscow
RUN ln -sf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN mkdir -p /var/cs/s3store/data 
RUN touch /etc/default/minio && \
    echo 'MINIO_VOLUMES="/var/cs/s3store/data/"' >> /etc/default/minio && \
    echo 'MINIO_OPTS="--address :9000 --console-address :9001"' >> /etc/default/minio && \
    echo "MINIO_ROOT_USER=${MINIO_ROOT_USER}" >> /etc/default/minio && \
    echo "MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}" >> /etc/default/minio && \
    echo 'MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY_ID}' >> /etc/default/minio && \
    echo 'MINIO_SECRET_KEY=${MINIO_SECRET_KEY}' >> /etc/default/minio 

COPY ./init-scripts/* /docker-entrypoint-initdb.d/

RUN chmod +x /docker-entrypoint-initdb.d/init.sh
RUN chmod +x /docker-entrypoint-initdb.d/entrypoint.sh

ENTRYPOINT ["/docker-entrypoint-initdb.d/entrypoint.sh"]